var en={dir:{right:0,up:1,left:2,down:3},act:{norm:0,attack:1,push:2,regen:3},state:{norm:0,damage:1,dead:2}};function random(a){var rand=Math.random()*10;if(rand-5>0&&a<60)return a+1;else if(rand-5<=0&&a>40)return a-1;else return a}function srandom(a){var rand=Math.random()*10;if(rand>5)return a+1;else return a-1}function mxrandom(a){var rand=Math.random()*10;if(rand>5&&a<w-wx-10)return a+1;else if(rand<=5&&a>10)return a-1;else return a}
function myrandom(a){var rand=Math.random()*10;if(rand>5&&a>10)return a-1;else if(rand<=5&&a<h-wy-10)return a+1;else return a}function randomLocation(a){if(Math.random()*10>=5)if(Math.random()*10>=5){a.esx=Math.random()*w;a.esy=-50*Math.random()-20}else{a.esx=Math.random()*w;a.esy=h+50*Math.random()+20}else if(Math.random()*10>=5){a.esx=-50*Math.random()-20;a.esy=Math.random()*h}else{a.esx=w+50*Math.random()+20;a.esy=Math.random()*h}}var HowTo=false;var score=0;var highscore=localStorage.getItem("highscore");
var background=new Image;background.src="http://www.photos-public-domain.com/wp-content/uploads/2011/02/crumpled-notebook-paper-texture.jpg";function pauseMenu(){if(ponce){if(pause)pause=false;else pause=true;ponce=false;effects.play("btn")}if(pause){ctx.fillStyle="rgba(225, 220, 212, 0.4)";ctx.fillRect(0,0,w,h);ctx.fillStyle="grey";ctx.font="50px monospace";ctx.fillText("PAUSE",w/2-ctx.measureText("Pause").width/2,h/2+10)}}
var Menu={draw:function(){var grd=ctx.createLinearGradient(0,0,w,0);grd.addColorStop(0,"#ffd6cc");grd.addColorStop(.8,"grey");grd.addColorStop(1,"#fffbf9");ctx.fillStyle="#fffbf9";ctx.fillRect(0,0,w,h);drawChar();ctx.fillStyle=grd;ctx.font="80px Arial Bold";ctx.fillText("BLOB MOB",w/2-ctx.measureText("BLOB MOB").width/2,100);ctx.font="30px Arial Bold";ctx.fillText("START",w/2-ctx.measureText("START").width/2,400);var grd1=ctx.createLinearGradient(0,0,w*3,0);grd1.addColorStop(0,"grey");grd1.addColorStop(1,
"white");ctx.fillStyle=grd1;ctx.font="15px sans-serif";var bottommenu="  About   -   HOW TO PLAY   -   Traczyk";ctx.fillText(bottommenu,w/2-ctx.measureText(bottommenu).width/2,h-10);ctx.fillRect(10,h-13,w/2-ctx.measureText(bottommenu).width/2-10,1);ctx.fillRect(w/2+ctx.measureText(bottommenu).width/2+10,h-13,w/2-ctx.measureText(bottommenu).width/2-10,1)}};
var Scene={drawStage:function(w,h){document.body.style.backgroundColor="#000000";ctx.fillStyle="#fffbf9";ctx.fillRect(0,0,w,h);ctx.drawImage(background,0,0,w,h);ctx.lineWidth=10;ctx.strokeRect(0,0,w,h)},drawHUD:function(w,h,player){ctx.fillStyle="black";ctx.fillRect(w/2,10,w/2-10,20);ctx.fillStyle=player.color;ctx.fillRect(w/2+1,11,player.health/100*(w/2-10)-2,18);ctx.fillStyle="black";ctx.fillRect(w*3/4+5,40,w/4-15,20);ctx.fillStyle="#33cc33";ctx.fillRect(w*3/4+6,41,player.power/50*(w/4-15)-2,18);
ctx.fillStyle="black";ctx.fillRect(w/2,40,w/4-5,20);ctx.fillStyle="blue";ctx.fillRect(w/2+1,41,(1-player.cool/50)*(w/4-5)-2,18);ctx.fillStyle="black";ctx.font="20px monospace";ctx.fillText("Score: "+score,18,28,w/2);ctx.fillText("High-Score: "+highscore,18,58,w/2)}};
function menu(){setHighScore();sx=150;sy=150;wx=200;wy=200;score=0;highscore=localStorage.getItem("highscore");titleTheme.play();var sessionME=setInterval(function(){ctx.clearRect(0,0,w,h);var grd=ctx.createLinearGradient(0,0,w,0);grd.addColorStop(0,"#ffd6cc");grd.addColorStop(.8,"grey");grd.addColorStop(1,"#fffbf9");ctx.fillStyle="#fffbf9";ctx.fillRect(0,0,w,h);drawChar();ctx.fillStyle=grd;ctx.font="80px Arial Bold";ctx.fillText("BLOB MOB",w/2-ctx.measureText("BLOB MOB").width/2,100);ctx.font="30px Arial Bold";
ctx.fillText("START",w/2-ctx.measureText("START").width/2,400);var grd1=ctx.createLinearGradient(0,0,w*3,0);grd1.addColorStop(0,"grey");grd1.addColorStop(1,"white");ctx.fillStyle=grd1;ctx.font="15px sans-serif";var bottommenu="  About   -   HOW TO PLAY   -   Traczyk";ctx.fillText(bottommenu,w/2-ctx.measureText(bottommenu).width/2,h-10);ctx.fillRect(10,h-13,w/2-ctx.measureText(bottommenu).width/2-10,1);ctx.fillRect(w/2+ctx.measureText(bottommenu).width/2+10,h-13,w/2-ctx.measureText(bottommenu).width/
2-10,1);if(pause===false){sx=mxrandom(sx);sy=myrandom(sy);wx=srandom(wx);wy=srandom(wy)}pauseMenu();listen();if(HowTo)HowToPlay();canvas.addEventListener("mousedown",getPosition,false);if(x>=w/2-ctx.measureText(bottommenu).width/2-5&&x<=w/2-ctx.measureText(bottommenu).width/2+55&&y>=h-30&&y<=h&&pause===false){clearInterval(sessionME);canvas.removeEventListener("mousedown",getPosition,false);window.location.href="/about.html"}if(x>=w/2-40&&x<=w/2+40&&y>=380&&y<=420&&pause===false){clearInterval(sessionME);
transition();canvas.removeEventListener("mousedown",getPosition,false)}else if(x>=w/2-ctx.measureText(bottommenu).width/4&&x<=w/2+ctx.measureText(bottommenu).width/4&&y>=h-30&&y<=h&&HowTo===false&&pause===false){effects.play("btn");HowTo=true;x=0;y=0}else if(x>=w/2-ctx.measureText(bottommenu).width/4&&x<=w/2+ctx.measureText(bottommenu).width/4&&y>=h-30&&y<=h&&HowTo||x>=w-35-ctx.measureText("X").width&&x<=h-30&&y>=30&&y<=60&&pause===false){effects.play("btn");HowTo=false;x=0;y=0}document.body.style.backgroundColor=
"#fffbf9"},50)}
function HowToPlay(){ctx.fillStyle="#ffd6cc";ctx.fillRect(30,30,w-60,h-60);ctx.fillStyle="black";ctx.font="20px monospace";ctx.fillText("X",w-35-ctx.measureText("X").width,50);var grd=ctx.createLinearGradient(0,0,w,0);grd.addColorStop(0,"#ffd6cc");grd.addColorStop(.5,"grey");grd.addColorStop(1,"#fffbf9");ctx.fillStyle=grd;ctx.font="50px Arial Bold";ctx.fillText("HOW TO PLAY",w/2-ctx.measureText("HOW TO PLAY").width/2,80);ctx.fillStyle="grey";ctx.font="15px monospace";var instruction1="Use the Arrow keys to move,";
var instruction2="And press Space to attack.";var instruction3="You can only attack if your blue bar is full!";var instruction4="Try to attack the enemies";var instruction5="But use Z, your powerup, if you are swarmed.";var instruction6="You can also hold X to regenerate health.";var instruction7="Just remember, powerups and regeneration use power!";var instruction8="Press M to mute and P to pause";ctx.fillText(instruction1,w/2-ctx.measureText(instruction1).width/2,122);ctx.fillText(instruction2,
w/2-ctx.measureText(instruction2).width/2,154);ctx.fillText(instruction3,w/2-ctx.measureText(instruction3).width/2,186);ctx.fillText(instruction4,w/2-ctx.measureText(instruction4).width/2,218);ctx.fillText(instruction5,w/2-ctx.measureText(instruction5).width/2,250);ctx.fillText(instruction6,w/2-ctx.measureText(instruction6).width/2,282);ctx.fillText(instruction7,w/2-ctx.measureText(instruction7).width/2,314);ctx.fillStyle="red";ctx.fillText(instruction8,w/2-40,463);var esx=380;var esy=390;var ewx=
20;var ewy=40;ctx.lineWidth=1;randNum=Math.round(Math.random()*2);var erandomColor=ecolors[randNum];ctx.fillStyle=erandomColor;ctx.beginPath();ctx.moveTo(esx-esx/20,esy);ctx.bezierCurveTo(esx-esx/20,esy-esy/20,esx+ewx+esx/20,esy-esy/20,esx+ewx+esx/20,esy);ctx.bezierCurveTo(esx+ewx+esx/10,esy,esx+ewx+esx/10,esy+ewy,esx+ewx,esy+ewy);ctx.bezierCurveTo(esx+ewx/10,esy+esy/4,esx-ewx*2,esy+ewy/4,esx-esx/20,esy+ewy/2);ctx.bezierCurveTo(esx-esx/20,esy+ewy/2,esx-ewx*2,esy+ewy/4,esx-esx/20,esy);ctx.fill();ctx.stroke();
ctx.closePath();ctx.lineWidth=1;ctx.beginPath();ctx.fillStyle="black";ctx.arc(esx+ewx/6,esy+ewy/6,(ewx/4+ewy/4)/4,0,2*Math.PI);ctx.stroke();ctx.closePath();ctx.beginPath();ctx.arc(esx+ewx-ewx/8,esy+ewy/6,(ewx/4+ewy/4)/6,0,2*Math.PI);ctx.stroke();ctx.closePath();ctx.beginPath();ctx.moveTo(esx+ewx/8,esy+ewy-ewy/3);ctx.bezierCurveTo(esx+ewy/8,esy+ewy,esx+ewx-ewy/8,esy+ewy,esx+ewx-ewy/8,esy+ewy-ewy/3);ctx.stroke();ctx.closePath();ctx.font="15px monospace";ctx.fillText("ENEMY",390-ctx.measureText("ENEMY").width/
2,360);ctx.fillStyle="black";ctx.fillRect(w/2-115/2+5,395,115,20);ctx.fillStyle="blue";ctx.fillRect(w/2+.5-115/2+5,396,113-0/50*113,18);ctx.fillStyle="black";ctx.fillText("COOL-DOWN BAR",w/2-ctx.measureText("COOL-DOWN BAR").width/2+5,360);ctx.fillStyle="black";ctx.fillRect((w-60)*(1/3)-90,395,115,20);ctx.fillStyle="#33cc33";ctx.font="10px monospace";ctx.fillText(20+"/50",(w-60)*(1/3)-90+52,409);ctx.fillRect((w-60)*(1/3)-90+1,396,20/50*113,18);ctx.font="15px monospace";ctx.fillStyle="black";ctx.fillText("POWER",
90,360)}
function transition(){var gw=0;var time=0;titleTheme.fade(1,0,7E3);titleTheme.on("fade",function(){titleTheme.stop()});var sessionT=setInterval(function(){time++;ctx.clearRect(0,0,w,h);var grd=ctx.createLinearGradient(0,0,w-gw,0);grd.addColorStop(0,"#ffd6cc");grd.addColorStop(.8,"grey");grd.addColorStop(1,"#fffbf9");ctx.fillStyle="#fffbf9";ctx.fillRect(0,0,w,h);drawChar();ctx.fillStyle=grd;ctx.font="80px Arial Bold";ctx.fillText("BLOB MOB",w/2-ctx.measureText("BLOB MOB").width/2,100);ctx.font="30px Arial Bold";
ctx.fillStyle=grd;ctx.fillText("START",w/2-ctx.measureText("START").width/2,400);var grd1=ctx.createLinearGradient(0,0,w*3-gw*3,0);grd1.addColorStop(0,"grey");grd1.addColorStop(1,"white");ctx.fillStyle=grd1;ctx.font="15px sans-serif";var bottommenu="  About   -   HOW TO PLAY   -   Traczyk";ctx.fillText(bottommenu,w/2-ctx.measureText(bottommenu).width/2,h-10);ctx.fillRect(10,h-13,w/2-ctx.measureText(bottommenu).width/2-10,1);ctx.fillRect(w/2+ctx.measureText(bottommenu).width/2+10,h-13,w/2-ctx.measureText(bottommenu).width/
2-10,1);if(time<40){titleTheme.rate(1.5);if(time%2===0){wx-=4;wy-=4;sx+=2;sy+=2}else if(Math.abs(time%2)==1){wx+=4;wy+=4;sx-=2;sy-=2}}else if(time>=40){titleTheme.rate(.75);if(gw<=w-50)gw+=25;sx+=2;sy+=2;sx=srandom(sx);sy=srandom(sy);wx-=4;wy-=4}if(wx<=50||wy<=10){mainTheme.play();background.src="http://www.photos-public-domain.com/wp-content/uploads/2011/02/crumpled-notebook-paper-texture.jpg";ctx.drawImage(background,0,0,w,h);clearInterval(sessionT);main()}},50)}
function shrink(){var shrinksx=sx;var shrinksy=sy;var shrinkwx=wx;var shrinkwy=wy;var sessionS=setInterval(function(){de=effects.play("death");ctx.clearRect(0,0,w,h);drawStage();shrinksx+=4;shrinksy+=4;shrinkwx-=8;shrinkwy-=8;ctx.fillStyle=pcolor;ctx.fillRect(shrinksx,shrinksy,shrinkwx,shrinkwy);stateDefinition();drawHealth();drawPower();drawCool();drawScore();if(shrinkwx<=0||shrinkwy<=0||shrinksx>w||shrinksy>h){clearInterval(sessionS);end()}},150)}
function end(){var gx=-w;var gx2=-.5*w;effects.stop(ah);mainTheme.stop();endTheme.play();var sessionE=setInterval(function(){if(gx!==0)gx+=4;if(gx2!==0+200)gx2+=14;setHighScore();pcolor="#ffd6cc";ctx.clearRect(0,0,w,0);ctx.fillStyle="black";ctx.fillRect(0,0,h,w);var grd=ctx.createLinearGradient(0,0,w+gx,0);grd.addColorStop(0,pcolor);grd.addColorStop(1,"black");ctx.font="70px Comic Sans MS";ctx.fillStyle=grd;ctx.fillText("GAME OVER",w/2-ctx.measureText("GAME OVER").width/2,h/2-5);ctx.font="12px monospace";
if(highscore<score){ctx.fillText("The high score was "+highscore,w/2-ctx.measureText("The high score was "+highscore).width/2,h*8.5/16);ctx.fillText("Your score is "+score,w/2-ctx.measureText("Your score is "+score).width/2,h*9/16)}else{ctx.fillText("The high score is "+highscore,w/2-ctx.measureText("The high score is "+highscore).width/2,h*8.5/16);ctx.fillText("Your score was "+score,w/2-ctx.measureText("Your score was "+score).width/2,h*9/16)}ctx.font="20px monospace";var grd2=ctx.createLinearGradient(0,
0,w+gx2,0);grd2.addColorStop(0,pcolor);grd2.addColorStop(1,"black");ctx.fillStyle=grd2;ctx.fillText("TITLE >>",w-ctx.measureText("TITLE >>").width,h-10);canvas.addEventListener("mousedown",getPosition,false);if(x>=w-ctx.measureText("TITLE >>").width-10&&x<=w&&y>=h-20&&y<=h){clearInterval(sessionE);location.reload()}},50)}var x;var y;var keyState={pressed:{right:false,up:false,left:false,down:false,attack:false}};var keyMap={39:"right",38:"up",37:"left",40:"down",32:"attack"};
function listen(){function keyDownHandler(e){var key=keyMap[e.keyCode];keyState.pressed[key]=true}function keyUpHandler(e){var key=keyMap[e.keyCode];keyState.pressed[key]=false}document.addEventListener("keydown",keyDownHandler,false);document.addEventListener("keyup",keyUpHandler,false)}function getPosition(event){x=event.x;y=event.y;x-=c.offsetLeft;y-=c.offsetTop}
function setHighScore(){if(highscore!==null){if(score>highscore)localStorage.setItem("highscore",score)}else{highscore=0;localStorage.setItem("highscore",score)}}var clamp=function(num,min,max){return Math.min(Math.max(num,min),max)};var Player=function(x,y,w,h){this.x=x;this.y=y;this.w=w;this.h=h;this.xdir=1;this.ydir=0;this.color="#ffd6cc";this.maxSpeed=3;this.accel=.1;this.xvel=0;this.yvel=0;this.cool=0;this.power=50;this.health=100;this.action=en.act.norm;this.timer=0;this.state=en.state.norm};
Player.prototype.draw=function(){ctx.fillStyle=this.color;ctx.fillRect(this.x,this.y,this.w,this.h);ctx.lineWidth=1;ctx.beginPath();ctx.fillStyle="black";ctx.arc(this.x+this.w/6,this.y+this.h/6,(this.w/4+this.h/4)/4,0,2*Math.PI);ctx.stroke();ctx.closePath();ctx.beginPath();ctx.arc(this.x+this.w-this.w/8,this.y+this.h/6,(this.w/4+this.h/4)/6,0,2*Math.PI);ctx.stroke();ctx.closePath();ctx.beginPath();ctx.moveTo(this.x+this.w/8,this.y+this.h-this.h/3);ctx.bezierCurveTo(this.x+this.h/8,this.y+this.h,this.x+
this.w-this.h/8,this.y+this.h,this.x+this.w-this.h/8,this.y+this.h-this.h/3);ctx.stroke();ctx.closePath()};Player.prototype.controller=function(keys){if(this.cool<=0)if(keys.pressed.attack)this.action=en.act.attack;switch(this.action){case en.act.norm:this.move(keys.pressed);break;case en.act.attack:this.attack(20);break}this.x+=this.xvel;this.y+=this.yvel};
Player.prototype.move=function(dir){if(dir.right)this.xvel+=this.accel;if(dir.left)this.xvel-=this.accel;if(dir.down)this.yvel+=this.accel;if(dir.up)this.yvel-=this.accel;if(!dir.right&&!dir.left)if(Math.abs(this.xvel)<=this.accel)this.xvel=0;else if(this.xvel>0)this.xvel-=this.accel;else if(this.xvel<0)this.xvel+=this.accel;if(!dir.down&&!dir.up)if(Math.abs(this.yvel)<=this.accel)this.yvel=0;else if(this.yvel>0)this.yvel-=this.accel;else if(this.yvel<0)this.yvel+=this.accel;this.xvel=clamp(this.xvel,
-this.maxSpeed,this.maxSpeed);this.yvel=clamp(this.yvel,-this.maxSpeed,this.maxSpeed);this.calculateDir();if(this.cool>0){--this.cool;this.color="#adedff"}else this.color="#ffd6cc";this.wiggle();return 1};Player.prototype.calculateDir=function(){var mag=Math.sqrt(this.xvel*this.xvel+this.yvel*this.yvel);if(mag>0){this.xdir=this.xvel/mag;this.ydir=this.yvel/mag}};
Player.prototype.attack=function(duration){this.color="#adedff";++this.timer;this.cool+=50/duration;if(this.timer<duration/2){this.x+=this.xdir*5;this.y+=this.ydir*5}if(this.timer>duration/2){this.x-=this.xdir*5;this.y-=this.ydir*5}if(this.timer>=duration){this.xvel=0;this.yvel=0;this.timer=0;this.action=en.act.norm}};
Player.prototype.wiggle=function(){var rand=Math.random()>.5?1:-1;this.x=this.x+rand;rand=Math.random()>.5?1:-1;this.y=this.y+rand;rand=Math.random()>.5?1:-1;this.w=clamp(this.w+rand,40,60);rand=Math.random()>.5?1:-1;this.h=clamp(this.h+rand,40,60)};
function attack(){var time=0;at=effects.play("attack");var sessionA=setInterval(function(){pcolor="#adedff";time++;cool++;ctx.clearRect(0,0,w,h);drawStage();drawChar();stateDefinition();drawHealth();drawPower();drawCool();drawScore();if(time<5&&recent=="right")this.x+=10;else if(time<5&&recent=="left")this.x-=10;else if(time>5&&recent=="left")this.x+=10;else if(time>5&&recent=="right")this.x-=10;if(time<5&&recent=="down")this.y+=10;else if(time<5&&recent=="up")this.y-=10;else if(time>5&&recent=="up")this.y+=
10;else if(time>5&&recent=="down")this.y-=10;enemies.forEach(function(item,index,arr){if(time==5&&touch(item)&&item.state!="dead")arr[index].state="dying"});if(time>=10){effects.stop(ah);clearInterval(sessionA);attackb=false;main()}else if(collide()){effects.stop(ah);clearInterval(sessionA);shrink()}},50)}
function attackZ(){var time=0;r=3;mainTheme.mute(true);effects.stop(ah);pu=effects.play("push");var sessionAZ=setInterval(function(){pcolor="#adedff";time++;ctx.clearRect(0,0,w,h);if(7>=time){r--;cool+=2}else if(time>=8&&time<20&&time%2===0){r-=3;cool+=2}else if(time>=8&&time<20&&Math.abs(time%2)==1){r+=3;cool+=3}else if(20<=time&&time<30){enemies.forEach(function(item,index,arr){arr[index].state="push"});power--;r+=10;cool+=.5}drawStage();drawChar();stateDefinition();ctx.beginPath();ctx.strokeStyle=
pcolor;ctx.arc(this.x+this.w/2,this.y+this.h/2,this.w+r,0,2*Math.PI);ctx.stroke();ctx.closePath();ctx.strokeStyle="black";drawHealth();drawPower();drawCool();drawScore();if(time>=50){clearInterval(sessionAZ);attackz=false;main();enemies.forEach(function(item,index,arr){arr[index].state="alive"});cool+=1}else if(collide()){clearInterval(sessionAZ);attackz=false;shrink();enemies.forEach(function(item,index,arr){arr[index].state="alive"})}},50)}
function regenerate(){if(cool==50){justRegen=true;mainTheme.mute(true);if(effects.playing(he)!==true)he=effects.play("heal");effects.volume(1,he);if(power<=0){regeneration=false;attackx=false}if(Otime%3===0&&power>0)power-=1;if(health<100)health++;if(Otime%2===0){this.w+=5;this.h+=5;this.x-=2;this.y-=2}else{this.w-=4;this.h-=4;this.x+=2;this.y+=2}}else;}var basicEnemySpeed=.1;
var Enemy=function(enemspeed){this.x=0;this.y=0;this.w=50;this.h=50;this.speed=enemspeed*basicEnemySpeed;this.target;this.rcolors=["#81ea25","#6bba27","#96e84e","#abf966","#b9f981"];this.color=this.rcolors[0];this.state=en.state.spawn};Enemy.prototype.spawn=function(w,h,target){if(w==null||h==null){w=500;h=500}var rand=Math.random()*w;this.x=rand;rand=Math.random()*h;this.y=rand;this.target=target;this.state=en.state.norm;console.log("SPAWN")};
Enemy.prototype.draw=function(){if(this.state==en.state.spawn)return 0;ctx.lineWidth=1;var rand=Math.round(Math.random()*2);this.color=this.rcolors[rand];ctx.fillStyle=this.color;if(this.target!=null){this.w=this.target.w/2-10;this.h=this.target.h-10}ctx.beginPath();ctx.moveTo(this.x-this.w/8,this.y);ctx.bezierCurveTo(this.x-this.w/8,this.y-this.h/4,this.x+this.w+this.w/8,this.y-this.h/4,this.x+this.w+this.w/8,this.y);ctx.bezierCurveTo(this.x+this.w*2,this.y,this.x+this.w*2,this.y+this.h,this.x+this.w-
this.w/8,this.y+this.h);ctx.bezierCurveTo(this.x+this.w-this.w/8,this.y+this.h*1.75,this.x-this.w*2,this.y+this.h/4,this.x,this.y+this.h/2);ctx.bezierCurveTo(this.x-this.w,this.y+this.h/2,this.x-this.w/2,this.y,this.x-this.w/8,this.y);ctx.fill();ctx.stroke();ctx.closePath();ctx.lineWidth=1;ctx.beginPath();ctx.fillStyle="black";ctx.arc(this.x+this.w/6,this.y+this.h/6,(this.w/4+this.h/4)/4,0,2*Math.PI);ctx.stroke();ctx.closePath();ctx.beginPath();ctx.arc(this.x+this.w-this.w/8,this.y+this.h/6,(this.w/
4+this.h/4)/6,0,2*Math.PI);ctx.stroke();ctx.closePath();ctx.beginPath();ctx.moveTo(this.x+this.w/8,this.y+this.h);ctx.bezierCurveTo(this.x+this.h/8,this.y+this.h-this.h/3,this.x+this.w-this.h/8,this.y+this.h-this.h/3,this.x+this.w-this.h/8,this.y+this.h);ctx.stroke();ctx.closePath()};
Enemy.prototype.move=function(){if(this.target==null||this.state!=en.state.norm)return 0;if(this.x>this.target.x+this.target.w/10)this.x-=this.speed;if(this.x<this.target.x+this.target.w/10)this.x+=this.speed;if(this.y>this.target.y+this.target.h/10)this.y-=this.speed;if(this.y<this.target.y+this.target.h/10)this.y+=this.speed;this.wiggle()};Enemy.prototype.wiggle=function(){var rand=Math.random()>.5?1:-1;this.x=this.x+rand;rand=Math.random()>.5?1:-1;this.y=this.y+rand};
Enemy.prototype.kill=function(){this.w-=2;this.h-=2;ctx.moveTo(this.x-this.w/8,this.y);ctx.bezierCurveTo(this.x-this.w/8,this.y-this.h/4,this.x+this.w+this.w/8,this.y-this.h/4,this.x+this.w+this.w/8,this.y);ctx.bezierCurveTo(this.x+this.w*2,this.y,this.x+this.w*2,this.y+this.h,this.x+this.w-this.w/8,this.y+this.h);ctx.bezierCurveTo(this.x+this.w-this.w/8,this.y+this.h*1.75,this.x-this.w*2,this.y+this.h/4,this.x,this.y+this.h/2);ctx.bezierCurveTo(this.x-this.w,this.y+this.h/2,this.x-this.w/2,this.y,
this.x-this.w/8,this.y);ctx.fill();ctx.stroke();ctx.closePath();if(this.w<=0||this.h<=0){effects.stop(ah);de=effects.play("death");score++;if(power<50)power+=1;this.state="dead";if(this.type=="boss")this.bossIsAlive=false}};
Enemy.prototype.push=function(){if(this.type=="regular")this.draw();else if(this.type=="boss")this.drawBoss();if(inarea(this)){if(this.x>sx+wx/10)this.x+=6;if(this.x<sx+wx/10)this.x-=6;if(this.y>sy+wy/10)this.y+=6;if(this.y<sy+wy/10)this.y-=6}else{this.x=srandom(this.x);this.y=srandom(this.y)}};
function stateDef(a){if(a.type=="regular")if(a.state=="spawn"||a.state=="dead")a.spawn();else if(a.state=="alive"){if(pause===false)a.move();a.draw()}else if(a.state=="dying")a.kill();else{if(a.state=="push")a.push()}else if(a.type=="boss")if(a.state=="spawn")a.spawn();else if(a.state=="alive"){if(pause===false)a.move();a.drawBoss()}else if(a.state=="dying")a.kill();else if(a.state=="push")a.push()}
function stateDefinition(){stateDef(enemy1);stateDef(enemy2);stateDef(enemy3);stateDef(enemy4);stateDef(enemy5);stateDef(enemy6);stateDef(enemy7);stateDef(enemy8);stateDef(enemy9);stateDef(enemy10);stateDef(enemy11);stateDef(enemy12);stateDef(enemy13);stateDef(enemy14);stateDef(enemy15)}
function enemySpawn(){if(Otime==20)enemy1.state="spawn";if(Otime==100)enemy2.state="spawn";if(Otime==300)enemy3.state="spawn";if(Otime==500)enemy4.state="spawn";if(Otime==800)enemy5.state="spawn";if(Otime==1E3)enemy6.state="spawn";if(Otime==1500)enemy7.state="spawn";if(Otime==1800)enemy8.state="spawn";if(Otime==2E3)enemy9.state="spawn";if(Otime==2500)enemy10.state="spawn";if(Otime==3E3)enemy11.state="spawn";if(Otime==3500)enemy12.state="spawn";if(Otime==4E3){enemy13.state="spawn";enemy14.state="spawn";
enemy15.state="spawn"}}function enemeySpeed(){if(score>=20&&score<40)speed=1.2;if(score>=40&&score<80)speed=1.25;if(score>=80&&score<100)speed=1.5;if(score>=100&&score<200)speed=1.75;if(score>=200&&score<250)speed=2;if(score>=250&&score<300)speed=2.5;if(score>=300)speed=3}"use strict";var c=document.getElementById("canvas");var ctx=c.getContext("2d");var p=new Player(250,250,50,50);var fps=60;var wgame,hgame;var frameNumber=0;var gtime=0;var enemies=new Array;var e=new Enemy(5);var espawncool=0;
function resizeWindow(){ctx.canvas.width=window.innerWidth;ctx.canvas.height=window.innerHeight;wgame=window.innerWidth;hgame=window.innerHeight}function update(){listen();p.controller(keyState);enemies.forEach(function(enemy){return enemy.move()});if(espawncool>0)--espawncool;if(gtime%5&&enemies.length<15&&espawncool<=0){e=new Enemy(4);e.spawn(wgame,hgame,p);enemies.push(e);espawncool=500}}
function draw(){resizeWindow();ctx.clearRect(0,0,wgame,hgame);Scene.drawStage(wgame,hgame);p.draw();Scene.drawHUD(wgame,hgame,p);enemies.forEach(function(enemy){return enemy.draw()})}function main(){if(frameNumber==0)Scene.init;++frameNumber;gtime=Math.floor(frameNumber/fps*100)/100;update(frameNumber);draw();setTimeout(function(){window.requestAnimationFrame(main)},1E3/fps)}window.requestAnimationFrame(main);
